<?php
/**
 * Test script to demonstrate the ticket reply functionality with notifications.
 *
 * This script creates a ticket and then adds a reply to test:
 * - Reply creation with text content
 * - Notifications to ticket creator
 * - Notifications to CC contacts (known_emails)
 * - Support for attachments
 *
 * Run with: php scripts/test_ticket_reply.php
 */

require __DIR__ . '/../vendor/autoload.php';

$app = require_once __DIR__ . '/../bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Ticket;
use App\Models\TicketMessage;
use App\Models\User;
use App\Models\Inbox;

echo "=== Testing Ticket Reply System ===\n\n";

// 1. Create or get test user
echo "1. Creating/getting test user...\n";
$user = User::firstOrCreate(
    ['email' => 'test@example.com'],
    [
        'name' => 'Test User',
        'password' => bcrypt('password'),
    ]
);
echo "   User: {$user->name} ({$user->email})\n\n";

// 2. Create or get test inbox
echo "2. Creating/getting test inbox...\n";
$inbox = Inbox::firstOrCreate(
    ['slug' => 'test-inbox'],
    ['name' => 'Test Inbox']
);
echo "   Inbox: {$inbox->name}\n\n";

// 3. Create a ticket with known_emails (CC contacts)
echo "3. Creating ticket with CC contacts...\n";
$ticket = Ticket::create([
    'inbox_id' => $inbox->id,
    'requester_id' => $user->id,
    'subject' => 'Test Ticket - Reply System',
    'content' => 'This ticket is for testing the reply notification system.',
    'known_emails' => [
        'cc1@example.com',
        'cc2@example.com',
    ],
]);
$ticket->refresh(); // Get the ticket_number generated by observer
echo "   Ticket created: {$ticket->ticket_number}\n";
echo "   Subject: {$ticket->subject}\n";
echo "   CC Contacts: " . implode(', ', $ticket->known_emails) . "\n\n";

// 4. Create a reply to the ticket
echo "4. Creating reply to ticket...\n";
$message = TicketMessage::create([
    'ticket_id' => $ticket->id,
    'user_id' => $user->id,
    'content' => "This is a test reply.\n\nIt should trigger notifications to:\n- Ticket creator\n- All CC contacts\n- Additional CC in this message",
    'cc' => ['cc3@example.com'], // Additional CC for this specific message
    'is_internal' => false,
]);
echo "   Reply created (ID: {$message->id})\n";
echo "   By: {$user->name}\n";
echo "   Additional CC: " . implode(', ', $message->cc) . "\n\n";

// 5. Simulate second reply (from different perspective)
echo "5. Creating second reply...\n";
$message2 = TicketMessage::create([
    'ticket_id' => $ticket->id,
    'user_id' => $user->id,
    'content' => "Another reply with more information.\n\nImages and attachments are also supported!",
    'is_internal' => false,
]);
echo "   Second reply created (ID: {$message2->id})\n\n";

// 6. Display expected notification recipients
echo "=== Expected Notification Recipients ===\n";
echo "For each reply, notifications should be sent to:\n";
echo "- Ticket creator: {$user->email}\n";
echo "- Ticket CC (known_emails): " . implode(', ', $ticket->known_emails) . "\n";
echo "- Message CC: " . implode(', ', $message->cc ?: []) . "\n";
echo "\nTotal unique recipients per reply: ~4 emails\n\n";

// 7. Check mail configuration
echo "=== Mail Configuration ===\n";
echo "MAIL_MAILER: " . config('mail.default') . "\n";
echo "Queue is being used for emails (delayed by MAIL_SEND_DELAY_MS)\n\n";

echo "=== Test Summary ===\n";
echo "✓ Ticket created: {$ticket->ticket_number}\n";
echo "✓ 2 replies created\n";
echo "✓ Observers should have queued notification emails\n";
echo "\nCheck:\n";
echo "- storage/logs/laravel.log (if MAIL_MAILER=log)\n";
echo "- Queue jobs table (if queue driver is database)\n";
echo "- Run: php artisan queue:work (to process queued notifications)\n";
